services:
  dpdk-base-service:
    container_name: dpdk-base-container
    build: 
      context: .
      dockerfile: Dockerfile
    image: dpdk-base:v1.0
    environment:
      - RTE_SDK=/opt/dpdk-23.11
    volumes:
      - ..:/workspaces:cached
      - /sys/bus/pci/drivers:/sys/bus/pci/drivers 
      - /sys/kernel/mm/hugepages:/sys/kernel/mm/hugepages 
      - /sys/devices/system/node:/sys/devices/system/node 
      - /dev:/dev
      - /lib/modules:/lib/modules
    command: sleep infinity
    network_mode: "host"
    privileged: true
